########################################################################################################################
#
#                                       General pipeline settings
#
#########################################################################################################################
# Having base dir will allow to move up and down to the directory or scripts, also able to used different settings of
# the pipeline.
BASE_DIR: "/home/RNASeq"

# temp dir for hpc only
TMPDIR: "/home/TMPDIR"

# List of samples containing runID, readgroupd, path to Fastq1 and Fastq2
# List of samples containing normals and tumour samples
MASTER_LIST: "/home/RNASeq/master_list.txt"

# if true, create start index for aligners

STAR_INDEX: false
SALMON_INDEX: true

# Chose program for rna counts
featureCounts: false
HTSeqCounts: false

# Adapter for cutadapt or just the quality trimming m20 q20
CUTADAPT:
  trimming: true
  removeadapter: false

########################################################################################################################
#
#                                       Genome reference files
#
#########################################################################################################################

# Bundle dir for GRCh37/b37 genome version, change the location for dir according to path of home directory
#BUNDLE_DIR: "/home/GATK_Bundle/b37"

# The GTF and primary fasta file was downloaded from https://www.gencodegenes.org/human/release_39lift37.html
# Nucleotide sequences of all transcripts on the reference chromosomes
REF: "/home/GATK_Bundle/b37/GRCh37.primary_assembly.genome.fa"

# It contains the comprehensive gene annotation originally created on the GRCh38 reference chromosomes, mapped to the GRCh37 primary 
# assembly with gencode-backmap. This is the main annotation file for most users
# Note that automated annotation ('ENSEMBL') was not mapped to GRCh37 in this release. The corresponding annotation was obtained from GENCODE 19
# Also note that some manually annotated ('HAVANA') genes did not map properly to GRCh37. 
# Their annotation was copied from GENCODE 19 if available, or they are completely absent otherwise.

GTF: "/home/GATK_Bundle/b37/gencode.v39lift37.annotation.gtf"

########################################################################################################################
#
#                                       Cutadapt settings and parameters
#
#########################################################################################################################
# Change the number of threads for Star aligner according to the available resources
cutadapt_pe: "-a CCTTAGGCAACCTGGTGGTCCCCCGCTCCCGGGAGGTCACCATATTGATG -g GCTCCGTTTCCGACCTGGGCCGGTTCACCCCTCCTTAGGCAACCTGGTGG -A CCTTAGGCAACCTGGTGGTCCCCCGCTCCCGGGAGGTCACCATATTGATG -G GCTCCGTTTCCGACCTGGGCCGGTTCACCCCTCCTTAGGCAACCTGGTGG"
extra: "--minimum-length 20 -q 20"

########################################################################################################################
#
#                                       STAR Aligner settings and parameters
#########################################################################################################################
# Change the number of threads for Star aligner according to the available resources
STAR_THREADS: 8

########################################################################################################################
#
#                                       Salmon Aligner settings and parameters
#
#########################################################################################################################

# For Salmon decoy aware index, follow this method https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/
SALMON_GTF: "/home/GATK_Bundle/b37/gentrome.fa.gz"
DECOYS: "/home/GATK_Bundle/b37/decoys.txt"
SALMON_THREADS: 8

########################################################################################################################
#
#                                       ARRIBA fusion catcher settings
#
#########################################################################################################################
BLACKLIST: "/home/GATK_Bundle/b37/arriba/blacklist_hg19_hs37d5_GRCh37_v2.2.1.tsv"
KNOWNFUSION: "/home/GATK_Bundle/b37/arriba/known_fusions_hg19_hs37d5_GRCh37_v2.2.1.tsv"
ARRIBA_THREADS: 5

########################################################################################################################
#
#                                       HTSeq settings and parameters
#
#########################################################################################################################
HTSEQ_THREADS: 5

########################################################################################################################
#
#                                       featureCounts settings and parameters
#
#########################################################################################################################
FC_THREADS: 5

########################################################################################################################
#
#                                       deeptools settings and parameters
#
#########################################################################################################################
DT_THREADS: 5
